//package com.wosloveslife.fantasy.dao.bean;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
//
//import org.json.JSONException;
//import org.json.JSONObject;
//
///**
// * Entity mapped to table "BFOLDER".
// */
//public class BFolder {
//
//    public final String _id;
//    public final String filePath;
//    public boolean isFiltered;
//
//    public BFolder(JSONObject jsonObject) throws JSONException {
//        _id = jsonObject.optString("_id", null);
//        filePath = jsonObject.getString("filePath");
//        isFiltered = jsonObject.optBoolean("isFiltered", true);
//    }
//
//    public BFolder(String _id, String filePath, Boolean isFiltered) {
//        this._id = _id;
//        this.filePath = filePath;
//        this.isFiltered = isFiltered;
//    }
//
//    @Override
//    public boolean equals(Object o) {
//        if (this == o) return true;
//        if (o == null || getClass() != o.getClass()) return false;
//
//        BFolder bFolder = (BFolder) o;
//
//        return filePath != null ? filePath.equals(bFolder.filePath) : bFolder.filePath == null;
//
//    }
//
//    @Override
//    public int hashCode() {
//        return filePath != null ? filePath.hashCode() : 0;
//    }
//
//    public JSONObject toJson() throws JSONException {
//        JSONObject jsonObject = new JSONObject();
//        jsonObject.put("_id", _id);
//        jsonObject.put("filePath", filePath);
//        jsonObject.put("isFiltered", isFiltered);
//        return jsonObject;
//    }
//
//    public JSONObject safeToJson() {
//        try {
//            return toJson();
//        } catch (JSONException e) {
//            e.printStackTrace();
//            return new JSONObject();
//        }
//    }
//}
