package com.wosloveslife.fantasy.dao.folder;

import android.database.sqlite.SQLiteDatabase;

import com.wosloveslife.fantasy.bean.BFolder;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class FolderDaoSession extends AbstractDaoSession {

    private final DaoConfig bFolderDaoConfig;

    private final FolderDao bFolderDao;

    public FolderDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bFolderDaoConfig = daoConfigMap.get(FolderDao.class).clone();
        bFolderDaoConfig.initIdentityScope(type);

        bFolderDao = new FolderDao(bFolderDaoConfig, this);

        registerDao(BFolder.class, bFolderDao);
    }
    
    public void clear() {
        bFolderDaoConfig.getIdentityScope().clear();
    }

    public FolderDao getBFolderDao() {
        return bFolderDao;
    }

}
