//package com.wosloveslife.fantasy.dao;
//
//import android.database.sqlite.SQLiteDatabase;
//
//import com.wosloveslife.fantasy.dao.bean.BFolder;
//import com.wosloveslife.fantasy.dao.bean.BMusic;
//
//import java.util.Map;
//
//import de.greenrobot.dao.AbstractDao;
//import de.greenrobot.dao.AbstractDaoSession;
//import de.greenrobot.dao.identityscope.IdentityScopeType;
//import de.greenrobot.dao.internal.DaoConfig;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig musicEntityDaoConfig;
//    private final DaoConfig bFolderDaoConfig;
//
//    private final MusicEntityDao musicEntityDao;
//    private final FolderDao bFolderDao;
//
//    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        musicEntityDaoConfig = daoConfigMap.get(MusicEntityDao.class).clone();
//        musicEntityDaoConfig.initIdentityScope(type);
//
//        bFolderDaoConfig = daoConfigMap.get(FolderDao.class).clone();
//        bFolderDaoConfig.initIdentityScope(type);
//
//        musicEntityDao = new MusicEntityDao(musicEntityDaoConfig, this);
//        bFolderDao = new FolderDao(bFolderDaoConfig, this);
//
//        registerDao(BMusic.class, musicEntityDao);
//        registerDao(BFolder.class, bFolderDao);
//    }
//
//    public void clear() {
//        musicEntityDaoConfig.getIdentityScope().clear();
//        bFolderDaoConfig.getIdentityScope().clear();
//    }
//
//    public MusicEntityDao getMusicEntityDao() {
//        return musicEntityDao;
//    }
//
//    public FolderDao getBFolderDao() {
//        return bFolderDao;
//    }
//}
