package com.wosloveslife.fantasy.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MUSIC_ENTITY".
 */
public class MusicEntity {

    private long _id;
    private String title;
    private String artist;
    private String titlePinyin;
    private String artistPinyin;
    private String album;
    private String path;
    private long duration;
    private long size;
    private boolean isOnline;
    private String genre;
    private int year;
    private int track;
    private int discId;
    private boolean isMusic;
    private boolean isAlarm;
    private boolean isRingtone;
    private boolean isPodcast;
    private boolean isNotification;
    private boolean isFavorite;
    private String belongTo;

    public MusicEntity() {
    }

    public MusicEntity(long _id) {
        this._id = _id;
    }

    public MusicEntity(long _id, String title, String artist, String titlePinyin, String artistPinyin, String album, String path, long duration, long size, boolean isOnline, String genre, int year, int track, int discId, boolean isMusic, boolean isAlarm, boolean isRingtone, boolean isPodcast, boolean isNotification, boolean isFavorite, String belongTo) {
        this._id = _id;
        this.title = title;
        this.artist = artist;
        this.titlePinyin = titlePinyin;
        this.artistPinyin = artistPinyin;
        this.album = album;
        this.path = path;
        this.duration = duration;
        this.size = size;
        this.isOnline = isOnline;
        this.genre = genre;
        this.year = year;
        this.track = track;
        this.discId = discId;
        this.isMusic = isMusic;
        this.isAlarm = isAlarm;
        this.isRingtone = isRingtone;
        this.isPodcast = isPodcast;
        this.isNotification = isNotification;
        this.isFavorite = isFavorite;
        this.belongTo = belongTo;
    }

    public long get_id() {
        return _id;
    }

    public void set_id(long _id) {
        this._id = _id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getTitlePinyin() {
        return titlePinyin;
    }

    public void setTitlePinyin(String titlePinyin) {
        this.titlePinyin = titlePinyin;
    }

    public String getArtistPinyin() {
        return artistPinyin;
    }

    public void setArtistPinyin(String artistPinyin) {
        this.artistPinyin = artistPinyin;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public long getDuration() {
        return duration;
    }

    public void setDuration(long duration) {
        this.duration = duration;
    }

    public long getSize() {
        return size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public boolean getIsOnline() {
        return isOnline;
    }

    public void setIsOnline(boolean isOnline) {
        this.isOnline = isOnline;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getTrack() {
        return track;
    }

    public void setTrack(int track) {
        this.track = track;
    }

    public int getDiscId() {
        return discId;
    }

    public void setDiscId(int discId) {
        this.discId = discId;
    }

    public boolean getIsMusic() {
        return isMusic;
    }

    public void setIsMusic(boolean isMusic) {
        this.isMusic = isMusic;
    }

    public boolean getIsAlarm() {
        return isAlarm;
    }

    public void setIsAlarm(boolean isAlarm) {
        this.isAlarm = isAlarm;
    }

    public boolean getIsRingtone() {
        return isRingtone;
    }

    public void setIsRingtone(boolean isRingtone) {
        this.isRingtone = isRingtone;
    }

    public boolean getIsPodcast() {
        return isPodcast;
    }

    public void setIsPodcast(boolean isPodcast) {
        this.isPodcast = isPodcast;
    }

    public boolean getIsNotification() {
        return isNotification;
    }

    public void setIsNotification(boolean isNotification) {
        this.isNotification = isNotification;
    }

    public boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public String getBelongTo() {
        return belongTo;
    }

    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo;
    }

}
