package com.wosloveslife.fantasy.dao;

import android.database.sqlite.SQLiteDatabase;

import com.wosloveslife.fantasy.bean.BMusic;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class MusicDaoSession extends AbstractDaoSession {

    private final DaoConfig musicEntityDaoConfig;

    private final MusicEntityDao musicEntityDao;

    public MusicDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicEntityDaoConfig = daoConfigMap.get(MusicEntityDao.class).clone();
        musicEntityDaoConfig.initIdentityScope(type);

        musicEntityDao = new MusicEntityDao(musicEntityDaoConfig, this);

        registerDao(BMusic.class, musicEntityDao);
    }
    
    public void clear() {
        musicEntityDaoConfig.getIdentityScope().clear();
    }

    public MusicEntityDao getMusicEntityDao() {
        return musicEntityDao;
    }

}
