package com.wosloveslife.fantasy.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BFOLDER".
 */
public class BFolder {

    private Long _id;
    private String filePath;
    private Boolean isFiltered;

    public BFolder() {
    }

    public BFolder(Long _id) {
        this._id = _id;
    }

    public BFolder(Long _id, String filePath, Boolean isFiltered) {
        this._id = _id;
        this.filePath = filePath;
        this.isFiltered = isFiltered;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Boolean getIsFiltered() {
        return isFiltered;
    }

    public void setIsFiltered(Boolean isFiltered) {
        this.isFiltered = isFiltered;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BFolder bFolder = (BFolder) o;

        return filePath != null ? filePath.equals(bFolder.filePath) : bFolder.filePath == null;

    }

    @Override
    public int hashCode() {
        return filePath != null ? filePath.hashCode() : 0;
    }
}
